# Generated by Django 6.0.4 on 2026-04-26 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cake_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=100)),
                ('cake_price', models.IntegerField()),
                ('cake_category', models.CharField(max_length=50)),
                ('cake_description', models.TextField()),
                ('cake_image', models.FileField(upload_to='images/')),
            ],
        ),
    ]
