# Generated by Django 6.0.4 on 2026-04-26 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_email', models.EmailField(max_length=254)),
                ('customer_password', models.CharField(max_length=100)),
                ('customer_phn', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='cart_tbl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=1)),
                ('cake', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminapp.cake_tbl')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customerapp.customer_table')),
            ],
        ),
    ]
